2020.03.21 08:47:30 LOG5[ui]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2020.03.21 08:47:30 LOG5[ui]: Compiled with OpenSSL 1.1.0g  2 Nov 2017
2020.03.21 08:47:30 LOG5[ui]: Running  with OpenSSL 1.1.1  11 Sep 2018
2020.03.21 08:47:30 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2020.03.21 08:47:30 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2020.03.21 08:47:30 LOG5[ui]: Reading configuration from file /home/alexandre/projects/StayHome/stunnel/stunnel.conf
2020.03.21 08:47:30 LOG5[ui]: UTF-8 byte order mark not detected
2020.03.21 08:47:30 LOG5[ui]: FIPS mode disabled
2020.03.21 08:47:30 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2020.03.21 08:47:30 LOG5[ui]: Configuration successful
2020.03.21 08:47:47 LOG5[0]: Service [https] accepted connection from 127.0.0.1:63025
2020.03.21 08:47:47 LOG3[0]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:47:47 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:47:47 LOG5[1]: Service [https] accepted connection from 127.0.0.1:63028
2020.03.21 08:47:47 LOG3[1]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:47:47 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:47:51 LOG5[2]: Service [https] accepted connection from 127.0.0.1:63031
2020.03.21 08:47:51 LOG3[2]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:47:51 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:47:51 LOG5[3]: Service [https] accepted connection from 127.0.0.1:63032
2020.03.21 08:47:51 LOG5[3]: s_connect: connected 127.0.0.1:8000
2020.03.21 08:47:51 LOG5[3]: Service [https] connected remote server from 127.0.0.1:63033
2020.03.21 08:47:51 LOG5[4]: Service [https] accepted connection from 127.0.0.1:63034
2020.03.21 08:47:51 LOG3[4]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:47:51 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:48:11 LOG5[5]: Service [https] accepted connection from 127.0.0.1:63061
2020.03.21 08:48:11 LOG3[5]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:48:11 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:48:30 LOG5[cron]: Updating DH parameters
2020.03.21 08:48:31 LOG5[cron]: DH parameters updated
2020.03.21 08:51:24 LOG5[6]: Service [https] accepted connection from 127.0.0.1:63275
2020.03.21 08:51:24 LOG3[6]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:51:24 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:51:24 LOG5[7]: Service [https] accepted connection from 127.0.0.1:63276
2020.03.21 08:51:24 LOG5[7]: s_connect: connected 127.0.0.1:8000
2020.03.21 08:51:24 LOG5[7]: Service [https] connected remote server from 127.0.0.1:63277
2020.03.21 08:52:02 LOG5[7]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:52:02 LOG5[8]: Service [https] accepted connection from 127.0.0.1:63321
2020.03.21 08:52:02 LOG3[8]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:52:02 LOG5[8]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:52:02 LOG5[9]: Service [https] accepted connection from 127.0.0.1:63322
2020.03.21 08:52:02 LOG5[9]: persistence: No cached address found
2020.03.21 08:52:02 LOG5[9]: s_connect: connected 127.0.0.1:8000
2020.03.21 08:52:02 LOG5[9]: Service [https] connected remote server from 127.0.0.1:63323
2020.03.21 08:52:13 LOG5[9]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:53:22 LOG5[10]: Service [https] accepted connection from 127.0.0.1:63403
2020.03.21 08:53:22 LOG3[10]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:53:22 LOG5[10]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:53:22 LOG5[11]: Service [https] accepted connection from 127.0.0.1:63404
2020.03.21 08:53:22 LOG5[11]: s_connect: connected 127.0.0.1:8000
2020.03.21 08:53:22 LOG5[11]: Service [https] connected remote server from 127.0.0.1:63405
2020.03.21 08:53:48 LOG5[11]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:53:48 LOG5[12]: Service [https] accepted connection from 127.0.0.1:63437
2020.03.21 08:53:48 LOG3[12]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:53:48 LOG5[12]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:53:48 LOG5[13]: Service [https] accepted connection from 127.0.0.1:63438
2020.03.21 08:53:48 LOG5[13]: persistence: No cached address found
2020.03.21 08:53:48 LOG5[13]: s_connect: connected 127.0.0.1:8000
2020.03.21 08:53:48 LOG5[13]: Service [https] connected remote server from 127.0.0.1:63439
2020.03.21 08:54:04 LOG5[13]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:55:01 LOG5[14]: Service [https] accepted connection from 127.0.0.1:63513
2020.03.21 08:55:01 LOG3[14]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:55:01 LOG5[14]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:55:01 LOG5[15]: Service [https] accepted connection from 127.0.0.1:63514
2020.03.21 08:55:01 LOG5[15]: s_connect: connected 127.0.0.1:8000
2020.03.21 08:55:01 LOG5[15]: Service [https] connected remote server from 127.0.0.1:63515
2020.03.21 08:55:23 LOG5[15]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:55:23 LOG5[16]: Service [https] accepted connection from 127.0.0.1:63538
2020.03.21 08:55:23 LOG3[16]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:55:23 LOG5[16]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:56:10 LOG5[17]: Service [https] accepted connection from 127.0.0.1:63586
2020.03.21 08:56:10 LOG3[17]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:56:10 LOG5[17]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:56:32 LOG5[18]: Service [https] accepted connection from 127.0.0.1:63609
2020.03.21 08:56:32 LOG3[18]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:56:32 LOG5[19]: Service [https] accepted connection from 127.0.0.1:63610
2020.03.21 08:56:32 LOG5[18]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:56:32 LOG5[19]: s_connect: connected 127.0.0.1:8000
2020.03.21 08:56:32 LOG5[19]: Service [https] connected remote server from 127.0.0.1:63611
2020.03.21 08:57:23 LOG5[19]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:57:24 LOG5[20]: Service [https] accepted connection from 127.0.0.1:63662
2020.03.21 08:57:24 LOG3[20]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:57:24 LOG5[20]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:57:31 LOG5[21]: Service [https] accepted connection from 127.0.0.1:63672
2020.03.21 08:57:31 LOG3[21]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:57:31 LOG5[21]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:57:31 LOG5[22]: Service [https] accepted connection from 127.0.0.1:63673
2020.03.21 08:57:31 LOG3[22]: s_connect: connect ::1:8000: Connection refused (111)
2020.03.21 08:57:31 LOG5[22]: s_connect: connected 127.0.0.1:8000
2020.03.21 08:57:31 LOG5[22]: Service [https] connected remote server from 127.0.0.1:63675
2020.03.21 08:57:41 LOG5[22]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:57:42 LOG5[23]: Service [https] accepted connection from 127.0.0.1:63686
2020.03.21 08:57:42 LOG3[23]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:57:42 LOG5[23]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:57:42 LOG5[24]: Service [https] accepted connection from 127.0.0.1:63687
2020.03.21 08:57:42 LOG5[24]: persistence: No cached address found
2020.03.21 08:57:42 LOG3[24]: s_connect: connect ::1:8000: Connection refused (111)
2020.03.21 08:57:42 LOG5[24]: s_connect: connected 127.0.0.1:8000
2020.03.21 08:57:42 LOG5[24]: Service [https] connected remote server from 127.0.0.1:63689
2020.03.21 08:58:01 LOG5[24]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 08:58:01 LOG5[25]: Service [https] accepted connection from 127.0.0.1:63710
2020.03.21 08:58:01 LOG3[25]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 08:58:01 LOG5[25]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:00:17 LOG5[26]: Service [https] accepted connection from 127.0.0.1:64153
2020.03.21 09:00:17 LOG3[26]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:00:17 LOG5[26]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:01:09 LOG5[27]: Service [https] accepted connection from 127.0.0.1:64412
2020.03.21 09:01:09 LOG3[27]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:01:09 LOG5[27]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:02:39 LOG5[28]: Service [https] accepted connection from 127.0.0.1:64515
2020.03.21 09:02:39 LOG3[28]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:02:39 LOG5[28]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:02:42 LOG5[29]: Service [https] accepted connection from 127.0.0.1:64523
2020.03.21 09:02:42 LOG3[29]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:02:42 LOG5[29]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:03:04 LOG5[30]: Service [https] accepted connection from 127.0.0.1:64546
2020.03.21 09:03:04 LOG3[30]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:03:04 LOG5[30]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:03:09 LOG5[31]: Service [https] accepted connection from 127.0.0.1:64552
2020.03.21 09:03:09 LOG3[31]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:03:09 LOG5[31]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:03:29 LOG3[3]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.03.21 09:03:29 LOG5[3]: Connection closed: 13577835 byte(s) sent to TLS, 54760 byte(s) sent to socket
2020.03.21 09:03:35 LOG5[32]: Service [https] accepted connection from 127.0.0.1:64580
2020.03.21 09:03:35 LOG3[32]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:03:35 LOG5[32]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:03:35 LOG5[33]: Service [https] accepted connection from 127.0.0.1:64581
2020.03.21 09:03:35 LOG5[33]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:03:35 LOG5[33]: Service [https] connected remote server from 127.0.0.1:64582
2020.03.21 09:03:35 LOG5[34]: Service [https] accepted connection from 127.0.0.1:64583
2020.03.21 09:03:35 LOG3[34]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:03:35 LOG5[35]: Service [https] accepted connection from 127.0.0.1:64584
2020.03.21 09:03:35 LOG5[34]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:03:35 LOG5[35]: persistence: No cached address found
2020.03.21 09:03:35 LOG5[35]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:03:35 LOG5[35]: Service [https] connected remote server from 127.0.0.1:64585
2020.03.21 09:04:14 LOG5[35]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:04:14 LOG5[36]: Service [https] accepted connection from 127.0.0.1:64624
2020.03.21 09:04:14 LOG3[36]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:04:14 LOG5[36]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:04:14 LOG5[37]: Service [https] accepted connection from 127.0.0.1:64625
2020.03.21 09:04:14 LOG5[37]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:04:14 LOG5[37]: Service [https] connected remote server from 127.0.0.1:64626
2020.03.21 09:04:48 LOG5[37]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:08:29 LOG5[38]: Service [https] accepted connection from 127.0.0.1:64930
2020.03.21 09:08:29 LOG3[38]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:08:29 LOG5[38]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:08:49 LOG5[39]: Service [https] accepted connection from 127.0.0.1:64961
2020.03.21 09:08:49 LOG3[39]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:08:49 LOG5[39]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:10:57 LOG5[40]: Service [https] accepted connection from 127.0.0.1:65112
2020.03.21 09:10:57 LOG3[40]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:10:57 LOG5[40]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:14:25 LOG5[41]: Service [https] accepted connection from 127.0.0.1:65349
2020.03.21 09:14:25 LOG3[41]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:14:25 LOG5[41]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:14:46 LOG5[42]: Service [https] accepted connection from 127.0.0.1:65379
2020.03.21 09:14:46 LOG3[42]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:14:46 LOG5[42]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:15:27 LOG5[43]: Service [https] accepted connection from 127.0.0.1:65428
2020.03.21 09:15:27 LOG3[43]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:15:27 LOG5[43]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:17:09 LOG5[44]: Service [https] accepted connection from 127.0.0.1:49152
2020.03.21 09:17:09 LOG3[44]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:17:09 LOG5[44]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:17:47 LOG5[45]: Service [https] accepted connection from 127.0.0.1:49198
2020.03.21 09:17:47 LOG3[45]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:17:47 LOG5[45]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:17:49 LOG5[46]: Service [https] accepted connection from 127.0.0.1:49202
2020.03.21 09:17:49 LOG3[46]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:17:49 LOG5[46]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:17:49 LOG5[47]: Service [https] accepted connection from 127.0.0.1:49203
2020.03.21 09:17:49 LOG5[47]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:17:49 LOG5[47]: Service [https] connected remote server from 127.0.0.1:49205
2020.03.21 09:27:13 LOG5[33]: Connection closed: 10875089 byte(s) sent to TLS, 58838 byte(s) sent to socket
2020.03.21 09:27:13 LOG5[47]: Connection closed: 4078541 byte(s) sent to TLS, 24924 byte(s) sent to socket
2020.03.21 09:27:13 LOG5[48]: Service [https] accepted connection from 127.0.0.1:49790
2020.03.21 09:27:13 LOG3[48]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:27:13 LOG5[48]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:27:13 LOG5[49]: Service [https] accepted connection from 127.0.0.1:49791
2020.03.21 09:27:13 LOG5[49]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:27:13 LOG5[49]: Service [https] connected remote server from 127.0.0.1:49792
2020.03.21 09:27:13 LOG5[50]: Service [https] accepted connection from 127.0.0.1:49793
2020.03.21 09:27:13 LOG3[50]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:27:13 LOG5[50]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:27:16 LOG5[51]: Service [https] accepted connection from 127.0.0.1:49805
2020.03.21 09:27:16 LOG3[51]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:27:16 LOG5[51]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:27:42 LOG5[52]: Service [https] accepted connection from 127.0.0.1:49831
2020.03.21 09:27:42 LOG3[52]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:27:42 LOG5[52]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:32:45 LOG5[49]: Connection closed: 2039379 byte(s) sent to TLS, 8214 byte(s) sent to socket
2020.03.21 09:37:37 LOG5[53]: Service [https] accepted connection from 127.0.0.1:50504
2020.03.21 09:37:37 LOG3[53]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:37:37 LOG5[54]: Service [https] accepted connection from 127.0.0.1:50505
2020.03.21 09:37:37 LOG5[53]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:37:37 LOG3[54]: s_connect: connect ::1:8000: Connection refused (111)
2020.03.21 09:37:37 LOG5[54]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:37:37 LOG5[54]: Service [https] connected remote server from 127.0.0.1:50507
2020.03.21 09:37:37 LOG5[55]: Service [https] accepted connection from 127.0.0.1:50508
2020.03.21 09:37:37 LOG3[55]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:37:37 LOG5[55]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:39:01 LOG5[56]: Service [https] accepted connection from 127.0.0.1:50672
2020.03.21 09:39:01 LOG3[56]: SSL_accept: 14094412: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
2020.03.21 09:39:01 LOG5[56]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:39:06 LOG5[57]: Service [https] accepted connection from 127.0.0.1:50679
2020.03.21 09:39:06 LOG5[57]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:39:06 LOG5[57]: Service [https] connected remote server from 127.0.0.1:50680
2020.03.21 09:41:35 LOG5[57]: Connection closed: 706107 byte(s) sent to TLS, 6899 byte(s) sent to socket
2020.03.21 09:43:06 LOG5[58]: Service [https] accepted connection from 127.0.0.1:65292
2020.03.21 09:43:06 LOG5[58]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:43:06 LOG5[58]: Service [https] connected remote server from 127.0.0.1:65293
2020.03.21 09:43:06 LOG3[58]: transfer() loop executes not transferring any data
2020.03.21 09:43:06 LOG3[58]: please report the problem to Michal.Trojnara@stunnel.org
2020.03.21 09:43:06 LOG3[58]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2020.03.21 09:43:06 LOG3[58]: Compiled with OpenSSL 1.1.0g  2 Nov 2017
2020.03.21 09:43:06 LOG3[58]: Running  with OpenSSL 1.1.1  11 Sep 2018
2020.03.21 09:43:06 LOG3[58]: Update OpenSSL shared libraries or rebuild stunnel
2020.03.21 09:43:06 LOG3[58]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2020.03.21 09:43:06 LOG3[58]: protocol=TLSv1.3, SSL_pending=0
2020.03.21 09:43:06 LOG3[58]: sock_open_rd=n, sock_open_wr=n
2020.03.21 09:43:06 LOG3[58]: SSL_RECEIVED_SHUTDOWN=Y, SSL_SENT_SHUTDOWN=n
2020.03.21 09:43:06 LOG3[58]: sock_can_rd=n, sock_can_wr=n
2020.03.21 09:43:06 LOG3[58]: ssl_can_rd=n, ssl_can_wr=Y
2020.03.21 09:43:06 LOG3[58]: read_wants_read=n, read_wants_write=n
2020.03.21 09:43:06 LOG3[58]: write_wants_read=n, write_wants_write=n
2020.03.21 09:43:06 LOG3[58]: shutdown_wants_read=n, shutdown_wants_write=n
2020.03.21 09:43:06 LOG3[58]: socket input buffer: 1377 byte(s), TLS input buffer: 0 byte(s)
2020.03.21 09:43:07 LOG5[58]: Connection reset: 7856 byte(s) sent to TLS, 917 byte(s) sent to socket
2020.03.21 09:43:16 LOG5[59]: Service [https] accepted connection from 127.0.0.1:65309
2020.03.21 09:43:17 LOG3[59]: SSL_accept: Peer suddenly disconnected
2020.03.21 09:43:17 LOG5[59]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:43:17 LOG5[60]: Service [https] accepted connection from 127.0.0.1:65310
2020.03.21 09:43:17 LOG5[60]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:43:17 LOG5[60]: Service [https] connected remote server from 127.0.0.1:65311
2020.03.21 09:43:35 LOG5[54]: Connection closed: 686066 byte(s) sent to TLS, 11893 byte(s) sent to socket
2020.03.21 09:45:12 LOG5[60]: Connection closed: 264 byte(s) sent to TLS, 427 byte(s) sent to socket
2020.03.21 09:48:27 LOG5[61]: Service [https] accepted connection from 127.0.0.1:57993
2020.03.21 09:48:27 LOG3[61]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:48:27 LOG5[61]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:48:27 LOG5[62]: Service [https] accepted connection from 127.0.0.1:57994
2020.03.21 09:48:27 LOG3[62]: s_connect: connect ::1:8000: Connection refused (111)
2020.03.21 09:48:27 LOG5[62]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:48:27 LOG5[62]: Service [https] connected remote server from 127.0.0.1:57996
2020.03.21 09:48:27 LOG5[63]: Service [https] accepted connection from 127.0.0.1:57997
2020.03.21 09:48:27 LOG3[63]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.03.21 09:48:27 LOG5[63]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.03.21 09:48:27 LOG5[64]: Service [https] accepted connection from 127.0.0.1:57998
2020.03.21 09:48:28 LOG5[64]: persistence: No cached address found
2020.03.21 09:48:28 LOG3[64]: s_connect: connect ::1:8000: Connection refused (111)
2020.03.21 09:48:28 LOG5[64]: s_connect: connected 127.0.0.1:8000
2020.03.21 09:48:28 LOG5[64]: Service [https] connected remote server from 127.0.0.1:58000
2020.03.21 09:49:14 LOG5[64]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
